# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Luke Berry
tagline:             ''
description:         'something, something, something'
url:                 http://luke-berry.co.uk
baseurl:             'http://luke-berry.co.uk'
paginate:            5

# About/contact
author:
  name:              Luke Berry
  url:               https://twitter.com/lukeberry99
  email:             contact@luke-berry.co.uk

# Custom vars
version:             1.0.0
